[[redirects]]
  from = "/"
  to = "https://mgofdc.org/"
  status = 301
  force = true

[[redirects]]
  from = "/ellington-arboretum/red-maple"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=j170"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/silver-maple"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=275381"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/sugar-maple"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=h240"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/red-buckeye"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=281049"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/serviceberry"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=h290"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/paw-paw"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=275970"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/river-birch"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=277830"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/bitternut-hickory"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=d375"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/pecan-hickory-pawnee"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=281352&isprofile=1&gen=Carya"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/pecan-hickory-lakota"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=281352&isprofile=1&gen=Carya"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/shellbark-hickory"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=281353&isprofile=1&gen=Carya"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/hackberry"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a858"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/eastern-redbud"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=h550"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/american-fringe-tree"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=c120"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/yellowwood"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a270"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/flowering-dogwood"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=c280"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/kousa-dogwood"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=j910"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/washington-hawthorn"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a861"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/japanese-cedar"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a158"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/common-persimmon"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=279917"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/american-beech"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a865"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/white-ash"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a867"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/ginkgo"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=z990"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/witch-hazel"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a749"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/american-holly"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=k640"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/black-walnut"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a875"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/eastern-red-cedar"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=279605"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/sweetgum"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=c116"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/tulip-poplar"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a878"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/osage-orange"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a879"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/southern-magnolia"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=c117"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/crab-apple-prairie-fire"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=u360"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/white-mulberry"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=d439"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/black-gum-black-tupelo"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a670"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/eastern-white-pine"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=285004"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/black-cherry"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=286398"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/sawtooth-oak"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=280732"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/white-oak"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=280711"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/shingle-oak"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a899"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/bur-oak"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a902"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/chinkapin-oak"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a903"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/willow-oak"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a191"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/red-oak"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=280723"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/shumard-oak"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=280724"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/baldcypress"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=m510"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/american-linden-basswood"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a917"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/eastern-hemlock"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?taxonid=285010"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/lacebark-elm"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=c158"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/vitex-lilac-chasetree"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=g290"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/japanese-elm"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a927"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/holly"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=c822"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/foster-holly-topal-holly"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=q190"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/large-flowered-magnolia"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=c823"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/little-leaf-linden"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=a918"
  status = 307

[[redirects]]
  from = "/ellington-arboretum/star-magnolia"
  to = "https://www.missouribotanicalgarden.org/PlantFinder/PlantFinderDetails.aspx?kempercode=l130"
  status = 307
